### ISSUE TITLE
New Api Bug

### ISSUE THREAD

**Issue by NycuRO** [PocketDreams/SequinLand#19]
Using transfer:

        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"Thread-0" Id=8 TIMED_WAITING on cn.nukkit.utils.MainLogger@52a23575
        at java.lang.Object.wait(Native Method)
        -  waiting on cn.nukkit.utils.MainLogger@52a23575
        at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:222)
        at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@1a4340f2
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@1a4340f2
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@56a63c28
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@56a63c28
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" Id=1 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
        at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:110)
        at cn.nukkit.Server.tickProcessor(Server.java:805)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:64)

Version, latest with New api from pocketmine.
Ubuntuu 14.04.5 LTS 64BIT.
1.0.3 , Windows 10 Edition.

**Comment by MrPowerGamerBR** [comment]
I need the entire stack trace, I doubt this would be caused by the new change.

**Comment by MrPowerGamerBR** [comment]
But, after taking a quick look at the error, it seems it is a issue with Nukkit's MainLogger (so it isn't a SequinLand issue).

Anyway, if you can reproduce again, send the full error.

**Comment by MrPowerGamerBR** [comment]
If it is the MainLogger, Nukkit's MainLogger is a complete mess and should be rewritten as soon as possible.

**Comment by NycuRO** [comment]
Use transfer and transfer to server for reproduce.

Not all times is reproduced.

**Comment by MrPowerGamerBR** [comment]
Will try to reproduce the issue later

Em 16 de fev de 2017 10:27, "NycuRO" <notifications@github.com> escreveu:
